<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0fdacd54c0d93f3cc04dc55498ad4a6e
{
    public static $prefixLengthsPsr4 = array (
        's' => 
        array (
            'splitbrain\\phpcli\\' => 18,
            'splitbrain\\PHPArchive\\' => 22,
        ),
        'd' => 
        array (
            'dokuwiki\\plugin\\upgrade\\HTTP\\' => 29,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'splitbrain\\phpcli\\' => 
        array (
            0 => __DIR__ . '/..' . '/splitbrain/php-cli/src',
        ),
        'splitbrain\\PHPArchive\\' => 
        array (
            0 => __DIR__ . '/..' . '/splitbrain/php-archive/src',
        ),
        'dokuwiki\\plugin\\upgrade\\HTTP\\' => 
        array (
            0 => __DIR__ . '/../..' . '/HTTP',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'helper_plugin_upgrade' => __DIR__ . '/../..' . '/helper.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0fdacd54c0d93f3cc04dc55498ad4a6e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0fdacd54c0d93f3cc04dc55498ad4a6e::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit0fdacd54c0d93f3cc04dc55498ad4a6e::$classMap;

        }, null, ClassLoader::class);
    }
}
