<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'splitbrain\\phpcli\\' => array($vendorDir . '/splitbrain/php-cli/src'),
    'splitbrain\\PHPArchive\\' => array($vendorDir . '/splitbrain/php-archive/src'),
    'dokuwiki\\plugin\\upgrade\\HTTP\\' => array($baseDir . '/HTTP'),
);
