<?php return array(
    'root' => array(
        'name' => 'splitbrain/dokuwiki-plugin-upgrade',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '12ddee6afb2df28dc2ec5fb9a27ae467ad616cce',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'splitbrain/dokuwiki-plugin-upgrade' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '12ddee6afb2df28dc2ec5fb9a27ae467ad616cce',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'splitbrain/php-archive' => array(
            'pretty_version' => '1.4.1',
            'version' => '1.4.1.0',
            'reference' => 'e45d0d9247742490ea87afc6c026f211424999c8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../splitbrain/php-archive',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'splitbrain/php-cli' => array(
            'pretty_version' => '1.3.5',
            'version' => '1.3.5.0',
            'reference' => '813410b23f9790a62620a79a4e87aed4c5c43e37',
            'type' => 'library',
            'install_path' => __DIR__ . '/../splitbrain/php-cli',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
